spring:
  application:
    name: finance-api

  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: Nicolas2006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

    spring:
      cache:
        type: caffeine
        caffeine:
          spec: maximumSize=500,expireAfterWrite=10m

  jwt:
    secret: "uma-chave-secreta-bem-longa-com-no-minimo-256-bits-troque-em-producao"
    access-expiration: 900000       # 15 minutos em ms
    refresh-expiration: 604800000   # 7 dias em ms